### ISSUE TITLE
[FEAT] Add toggle and reload command.

### ISSUE THREAD

**Issue by LordYarkan** [xCykrix/DynamicLights#13]
Hi,

The DynamicLights plugin is great, could you add these commands?
1- /dynamiclight reload: to reload the configuration and avoid restarting the server.
2- /dynamiclight toggle: those who do not want dynamiclight

I await your response, thank you

**Comment by xCykrix** [comment]
Hello @LordYarkan. I have added this to the roadmap to be included in (hopefully) the next release.

I will add the capability to reload `lights.yml` so the server does not require a restart to change what emits light and the light level, however, changes to config.yml WILL require a restart due to how events are registered and the culling is calculated.

**Comment by xCykrix** [comment]
Added by #14. This adds the following functionality:

- /dynamiclights reload (dynamiclights.reload) - Reloads changes to lights.yml
- /dynamiclights toggle (dynamiclights.toggle) - Allows players to independently choose to render lighting for their client.

After full testing and validation, this will be scheduled for release in v1.0.6.

Moving to Blocked until release.

**Comment by xCykrix** [comment]
Committed to main branch and scheduled for release.

**Comment by xCykrix** [comment]
Landed in v1.0.6.

https://github.com/xCykrix/DynamicLights/releases/tag/v1.0.6
https://www.spigotmc.org/resources/dynamiclights.110707/update?update=541012
