### ISSUE TITLE
[Suggestion] Customize Light Sources and Global Toggle

### ISSUE THREAD

**Issue by supertakeru** [xCykrix/DynamicLights#6]
Ability to change light level per block and have a global toggle in config.yml for dynamiclights lock would be nice features.

**Comment by xCykrix** [comment]
Hey @supertakeru,

I can definitely look to adding the ability to change and customize light levels in a configuration file. I'll probably use something like "lights.yml" to add this feature vs having it in config.yml.

In regards to a global toggle, are you looking for the ability to change the default state to off instead of on or disable the lock feature entirely?

**Comment by supertakeru** [comment]
Yes, I am looking for an option in the configuration.yml to be able to set it to disabled so that it does NOT block off-hand placing by default.

**Comment by xCykrix** [comment]
Thanks for the clarification @supertakeru. Both of these are currently in progress and probably will be released tomorrow at some point.

**Comment by xCykrix** [comment]
The features requested are added in dev. Doing testing and will be releasing it shortly.
